# Generated by Django 5.1.2 on 2024-11-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_created_at_post_created_post_author_post_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True),
        ),
    ]
